//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int IdImage { get; set; }
        public string ImagePath { get; set; }
        public int IdRestaurant { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
