//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseContext : DbContext
    {
        public DatabaseContext() : base("name=RestaurantDataEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<kitchen> kitchens { get; set; }
        public virtual DbSet<restaurant> restaurants { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<searchTerm> searchTerms { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
