//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class searchTerm
    {
        public int id_term { get; set; }
        public string name { get; set; }
        public int id_restaurant { get; set; }
    
        public virtual restaurant restaurant { get; set; }
    }
}
